#!/usr/bin/python
# -*- coding: UTF-8 -*-

# __modification time__ = 2025-02-16
# __author__ = Qi Zhou and Sibashish Dash, GFZ Helmholtz Centre for Geosciences
# __find me__ = qi.zhou@gfz.de, qi.zhou.geo@gmail.com, https://github.com/Qi-Zhou-Geo
# Please do not distribute this code without the author's permission

# catchment mapping, load as "dictionary" in python
# data structure for the following
# Illgraben-9J:
  # path_mapping: "European/Illgraben"
  # response_type: "xml" == with xml file,
                 # "simulate" == with poles and zeros,
                 # "direct" == # without poles and zeros
  # sensor_type: "do-not-need"
  # normalization_factor: 1) "do-not-need", 2) or use some number when "direct"


# Europen
Illgraben-9J:
  path_mapping: "European/Illgraben"
  response_type: "xml"
  sensor_type: "do-not-need"
  normalization_factor: "do-not-need"

Illgraben-9S:
  path_mapping: "European/Illgraben"
  response_type: "xml"
  sensor_type: "do-not-need"
  normalization_factor: "do-not-need"
